### ISSUE TITLE
'Broken pipe' error when streaming to vlc

### ISSUE THREAD

**Issue by robalar** [izderadicka/btclient#1]
when i attempt to steam via http to vlc I get this error:
```
Exception happened during processing of request from ('127.0.0.1', 40368)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by robalar** [comment]
On further investigation this is due to vlc not handling spaces in urls well

**Comment by izderadicka** [comment]
I do not have problem with spaces in url in VLC.   Could you share link to torrent to test it here?  Easily can add urllib.quote if spaces are really problem.

**Comment by robalar** [comment]
I solved the problem by launching vlc with the url encapsulated in quote marks (" ")
